### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by javatlacati** [joel-james/lazy-facebook-comments#2]
Looks nice how can I help you to translate it?

**Comment by joel-james** [comment]
Hi @javatlacati 

Thank you. You can help to translate from [here](https://translate.wordpress.org/projects/wp-plugins/lazy-facebook-comments).

**Comment by javatlacati** [comment]
https://translate.wordpress.org/locale/es-mx/default/wp-plugins/lazy-facebook-comments

Should I migrate changes to the other branches from that site too?

**Comment by joel-james** [comment]
No need. Let's wait for the translation editors to approve your translation. It will take some time.

Thank you so much for the help!
